name : Regression testing
on : push
jobs:
   cypress-run:
      runs-on: windows-latest
      steps : 
       - name: Checkout
         uses: actions/checkout@v4

       - name : Cypress run
         uses : Deepesh-Barsiwal/cypress-parallel-yml