name : Regression testing
on : push
jobs:
   cypress-run:
      runs-on: windows-latest
      steps : 
       - name: Checkout
         uses: actions/checkout@v2

       - name : Cypress run
         uses : cypress-parallel-yml/github-actions@v5.1.0